spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer:  org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
      group-id: tacoEater
      properties:
        spring.json.trusted.packages: tacos.tacoOrder